
server:
  port: 9002

spring:
  application:
    name: customer-center
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
      httpclient:
        hc5:
          enabled: true
      compression:
        request:
          enabled: true
          mime-types: text/xml,application/xml,application/json
          min-request-size: 2048


management:
  endpoints:
    web:
      exposure:
        include: '*'

service-url:
  nacos-user-center: http://user-center
