


server:
  port: 8999

spring:
  application:
    name: gateway-center
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: id-customer-center
          uri: lb://customer-center
          predicates:
            - Method=GET,POST,PUT,DELETE

management:
  endpoints:
    web:
      exposure:
        include: '*'
